// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Read env values safely. If either is missing (e.g. a stale build served
// without env injection), fall back to harmless placeholders so createClient
// does not throw at module load — which would white-screen the app before
// React mounts. The `supabaseConfigured` flag in src/lib/supabase.ts handles
// the "backend not configured" UX gracefully across the app.
// Hard fallbacks to the real publishable backend identity so the published
// bundle continues to authenticate even when Vite env injection is missing.
// These are public values (URL + publishable/anon key) — safe to ship.
const FALLBACK_SUPABASE_URL = 'https://pgimbjfdxwefahxmpdpc.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_iJUl_R_VWamc4p2eC2XAWw_3Li5jJ0t';

const SUPABASE_URL =
  (import.meta as any).env?.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Fallbacks são a identidade pública real do backend — quando o build vem
// sem env injetada (ex.: bundle publicado antigo), os fallbacks garantem que
// o client funcione sem ruído no console. Não há perda de segurança: tanto a
// URL quanto a publishable key são valores públicos por design.

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
